// Pre-defined location names in alphabetical order
const predefinedNames = [
  "Alpine",
  "B-2",
  "B-3",
  "Bear Paw",
  "Bitterroot #5",
  "Bitterroot Base",
  "Bitterroot Basin",
  "Bogus Creek Trail",
  "Bonanza",
  "Buckhorn",
  "Buttercup Trail",
  "Cabin Traverse",
  "Cascade",
  "Coach #7",
  "Coach's Corner",
  "Comeback",
  "Condominiums",
  "Corn Patch",
  "Cut-Off",
  "Deadwood",
  "Deer Point",
  "Deer Point Express #1",
  "Easy Rider",
  "Easy Way Down",
  "Eureka",
  "Frontier Point Lodge",
  "Good Enough",
  "Greenie's Run",
  "Grooming Trail",
  "Hogsback",
  "Ida Belle",
  "J.R. Simplot Lodge",
  "Jason Harper Training Center",
  "Lando's Mojo",
  "Last Chance",
  "Lazy Mary",
  "Liberty",
  "Lightning",
  "Lulu",
  "Lower Bonanza",
  "Lower Majestic",
  "Lower Nugget",
  "Lower Paradise",
  "Lower Ridge",
  "Lucky Friday",
  "Majestic",
  "Mambo Meadows",
  "Matchless",
  "Mid-Paradise",
  "Mike's Mambo",
  "Morning Star",
  "Morning Star Express #2",
  "Mother Lode",
  "Night Hawk",
  "Nitro",
  "Northslope",
  "Nugget Bowls",
  "Nugget Cat Track",
  "Omar's Inspiration",
  "Paradise",
  "Paradise Cat Track",
  "Pine Creek Base",
  "Pine Creek Bowl",
  "Pine Creek Express #6",
  "Pioneer",
  "Pioneer Lodge",
  "Pioneer Trail",
  "Playground",
  "Power Line",
  "Second Chance",
  "Shafer Butte",
  "Shaker Ridge",
  "Shamrock",
  "Shindig",
  "Showcase",
  "Showcase #4",
  "Silver Queen",
  "Sleepy Hollow",
  "Smuggler",
  "Smuggler Cut-Off",
  "Snoozer",
  "Sourdough",
  "Stewart's Bowl",
  "Stump Bowl",
  "Sunbeam",
  "Sunshine",
  "Sunset Bowl",
  "Superior",
  "Superior Express #3",
  "Tempest",
  "The Beach",
  "The Triangle",
  "Tiger",
  "Triumph",
  "Tubing Hill",
  "Uphill Skin Track",
  "Upper Nugget",
  "Upper Paradise",
  "Upper Ridge",
  "Wake Up Jim",
  "War Eagle",
  "Widowmaker",
  "Wildcat"
];

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
  module.exports = predefinedNames;
}
